### ISSUE TITLE
Permissions bug

### ISSUE THREAD

**Issue by degeneratehyperbola** [TobiasDeBruijn/DutchyTPA#2]
Plugin will sometimes print "You do not have permissions to use that command!" in the chat before executing the command.
The command itself works but this message pops up with no context.

Steps to reproduce:
- Run paper 1.16.3 with plugin loaded
- Optional: make a tpa request to any player
- Type /tpdeny or /tpno in the chat

Voila, you get this:

![image](https://user-images.githubusercontent.com/65950527/98816383-44ba7580-2431-11eb-98b0-2bf756cd9fd7.png)

**Comment by TobiasDeBruijn** [comment]
Fixed in 1.1.2. Thanks for letting me know!
